"""Synopsys (Design Compiler / PrimeTime) SDC backend (Step 6)."""

from __future__ import annotations

from ...constraint_model import ConstraintSet
from ...utils.enums import SafeMode
from ..generic.backend import GenericSDCBackend


class SynopsysSDCBackend(GenericSDCBackend):
    name = "synopsys"
    file_extension = ".sdc"

    def capabilities(self):
        caps = super().capabilities()
        caps.update({"mcmm": True, "set_propagated_clock": True,
                     "set_clock_transition": True, "design_rules": True,
                     "set_ideal_network": True, "set_dont_touch": True})
        return caps

    def header_lines(self, design_name: str, mode: SafeMode) -> list[str]:
        return [
            "# Synopsys SDC generated by RTL Constraint Assistant",
            f"# Design: {design_name}",
            f"# Safe mode: {mode.value}",
            "set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA",
            "",
        ]
