"""OpenSTA SDC backend (Step 6 hardened)."""

from __future__ import annotations

from io import StringIO

from ...constraint_model import ConstraintSet
from ...utils.enums import SafeMode
from ..generic.backend import GenericSDCBackend


class OpenSTASDCBackend(GenericSDCBackend):
    name = "opensta"
    file_extension = ".sdc"

    def capabilities(self):
        caps = super().capabilities()
        caps.update({"mcmm": True, "set_propagated_clock": True,
                     "set_clock_transition": True, "design_rules": True})
        return caps

    def header_lines(self, design_name: str, mode: SafeMode) -> list[str]:
        return [
            "# SDC for OpenSTA (generated by RCA)",
            f"# Design: {design_name}",
            f"# Safe mode: {mode.value}",
            "set_units -time ns -capacitance pF -resistance kOhm -voltage V -current mA",
            "",
        ]

    def render(self, cset: ConstraintSet, design_name: str = "top",
               mode: SafeMode = SafeMode.BALANCED, with_provenance: bool = True,
               scenario: str | None = None) -> str:
        return self.generate(cset, design_name=design_name, mode=mode,
                             with_provenance=with_provenance,
                             scenario=scenario).text
