# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

create_clock -name clk -period 10 -waveform { 0 5 } [get_ports clk]

