# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

create_clock -name clk -period 10 [get_ports clk]

create_generated_clock -name gclk -source [get_pins U/Q] -master_clock clk -divide_by 2 [get_pins U/Q]

