# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

create_generated_clock -name gp -source [get_pins U/Q] -master_clock clk -multiply_by 2 [get_pins U/Q]

