# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

set_input_delay -max -clock clk 2 [get_ports d]

set_input_delay -min -clock clk 0.5 [get_ports d]

set_output_delay -max -clock clk 3 [get_ports d]

set_output_delay -min -clock clk 0.8 [get_ports d]

