# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

set_clock_uncertainty -setup 0.1 [get_clocks clk]

set_clock_uncertainty -hold 0.2

