# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

set_clock_groups -asynchronous -group [get_clocks { a b }] -group [get_clocks c]

