# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

set_false_path -from [get_clocks A] -through [get_pins B] -through [get_pins C] -to [get_clocks D]

