# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

set_multicycle_path 2 -setup -from [get_clocks a] -to [get_clocks b]

