# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

set_min_delay 0.1 -from [get_clocks x] -to [get_ports y]

set_max_delay 5 -from [get_clocks x] -through [get_pins { A B }] -to [get_ports y]

