# SDC generated by RTL Constraint Assistant (generic backend)
# Design: golden
# Safe mode: balanced
# All time values in nanoseconds

set_driving_cell -lib_cell BUF_X1 [get_ports d]

set_input_transition 0.1 [get_ports d]

set_load 0.05 [get_ports q]

set_max_transition 0.5 [get_ports d]

