"""Cadence (Genus / Tempus) SDC backend (Step 6)."""

from __future__ import annotations

from ...constraint_model import ConstraintSet
from ...utils.enums import SafeMode
from ..generic.backend import GenericSDCBackend


class CadenceSDCBackend(GenericSDCBackend):
    name = "cadence"
    file_extension = ".sdc"

    def capabilities(self):
        caps = super().capabilities()
        caps.update({"mcmm": True, "set_propagated_clock": True,
                     "set_clock_transition": True, "design_rules": True})
        # Cadence Tempus does not support -edge_shift on create_generated_clock
        # in all older releases; mark it as unsupported to trigger diagnostic.
        caps["generated_clock_edge_shift"] = False
        return caps

    def header_lines(self, design_name: str, mode: SafeMode) -> list[str]:
        return [
            "# Cadence SDC (Genus/Tempus) generated by RTL Constraint Assistant",
            f"# Design: {design_name}",
            f"# Safe mode: {mode.value}",
            "",
        ]
